### ISSUE TITLE
PHp-mvc-rest-api 

### ISSUE THREAD

**Issue by syamasundararao** [afgprogrammer/php-mvc-simpel-rest-api#1]
I liked your project a lot.. But I got some problem while accessing an URL which contains parameters with spaces like /fetch-name/syam Sundararao .
If I gave this I got route not found... 
Please suggest me.. I studied your dispatch code. But unable to fix it...

**Comment by afgprogrammer** [comment]
Ok, I will fix it until tomorrow.

**Comment by syamasundararao** [comment]
Thanks for your reply

I got the output .. I changed the regular expresssion in dispatch method.

Thank you

**Comment by afgprogrammer** [comment]
Your welcome, I think it does not need to change the regular expression.
I just convert the space to -

**Comment by syamasundararao** [comment]
How can i upload image data along with request body in post method. Can you
give any example

Thanks in advance

**Comment by afgprogrammer** [comment]
It's simple but you should know how an upload file does it works in PHP.
https://www.tutorialspoint.com/php/php_file_uploading.htm

There is an example in the link above and I have also a global file variable, you can access it with 
$this->request->files('file-request-name'); in place of $_FILES[] in the Controllers file.

You can write it down and if you have any problem let me know.

**Comment by syamasundararao** [comment]
Please send a simple example if you have.. Post requests are always showing
route not found ..

Thanks

**Comment by afgprogrammer** [comment]
I make it for you, you can check it out.

send a post request to '/upload' with an image file.

I attached an image from the postman request.

![Screen Shot 2019-09-13 at 1 49 34 PM](https://user-images.githubusercontent.com/17293422/64851821-6b163280-d62d-11e9-997d-ae32c18b3ade.png)

**Comment by syamasundararao** [comment]
I too got upload image . But My Requirement is different . I have a form
contains so many fields along with image. How to post the data and image.

Thanks & Regards

**Comment by afgprogrammer** [comment]
It's so easy bro.
You can get all inputs with 
$this->request->post('variable_name_you_send_from_ui');
$this->request->input('variable_name_you_send_from_ui'); // This is another way for post request
or
$this->request->get('variable_name_you_send_from_ui');
or
$this->request->files['variable_name_you_send_from_ui'];

And if I make everything for you, you can't learn anything, so trying a little more.

**Comment by syamasundararao** [comment]
I have tried ... see the following attachment..

[image: image.png]

**Comment by afgprogrammer** [comment]
Sorry, your attachment does not show for me.

**Comment by syamasundararao** [comment]
$this->request->post[variable] shows an error of undefined property

**Comment by afgprogrammer** [comment]
Use like this: $this->request->post('variable')
not that becuse the "post" is a function not an array.

For more information please look at the Request.php

**Comment by syamasundararao** [comment]
D

**Comment by syamasundararao** [comment]
As per your suggestion I have used post as function .. I got the output if
I might not using the basin authentication . But i use basic authentication
then all variables are showing as NULL. Can you suggest me.

**Comment by afgprogrammer** [comment]
Sorry, I did not use with authentication, but if you have some error or issue, send them to me I see them and fix it or implement to this project.
