### ISSUE TITLE
Fatal error: Uncaught Exception: Class { MVC\Exception } Not Found!

### ISSUE THREAD

**Issue by mokhtasatxyz** [afgprogrammer/php-mvc-simpel-rest-api#13]
Hello
For me, this set of code (library) works fine in the local environment of the system
But when I upload and set it on my own subdomains, and I make a request, the following error message is received:

`Fatal error: Uncaught Exception: Class { MVC\Exception } Not Found! in /home/myshop/api/System/Startup.php:12 Stack trace: #0 [internal function]: autoload('MVC\\Exception') #1 /home/myshop/api/System/MVC/Controller.php(54): spl_autoload_call('MVC\\Exception') #2 /home/myshop/api/Application/Controllers/Buyer.php(192): MVC\Controller->model('buyer') #3 [internal function]: ControllersBuyer->find(Array) #4 /home/myshop/api/System/Router/Router.php(240): call_user_func(Array, Array) #5 /home/myshop/api/System/Router/Router.php(209): Router\Router->runController(Object(ControllersBuyer), Array) #6 /home/myshop/api/index.php(31): Router\Router->run() #7 {main} thrown in /home/myshop/api/System/Startup.php on line 12`

I checked, the received data and GET and POST parameters are received correctly and the error occurs when the model class is called
I think it is from the addressing in the config.php file or the autoload() function

**Comment by afgprogrammer** [comment]
@mokhtasatxyz  This error says that you are trying to load a class which its file is not exist. I think you might miss spell something and Ubuntu  servers are case sensitive.

**Comment by mokhtasatxyz** [comment]
Thank you
That was the problem
Uppercase and lowercase letters in file names and model names
