### ISSUE TITLE
Showing "not allowed"  in Postman every time i use get method

### ISSUE THREAD

**Issue by jayantrawat** [afgprogrammer/php-mvc-simpel-rest-api#2]
Hi, your work is really admirable. I am facing an issue. The response is working fine on the localhost but on the server, it returns the message "not allowed" when I use the GET method. On `POST` it works fine. I am sorry I don't want to put this as issue. But i tried multiple things and it isn't resolved the issue

**Comment by jayantrawat** [comment]
![image](https://user-images.githubusercontent.com/19587733/91179925-c76e4700-e704-11ea-80cb-b8f9451a844f.png)

**Comment by afgprogrammer** [comment]
I will check this issue by today and I will let you know.
