### ISSUE TITLE
Adding query parameters to URL route?

### ISSUE THREAD

**Issue by bradical1379** [afgprogrammer/php-mvc-simpel-rest-api#5]
Is it possible to pass additional query parameters on a route, and if so, how can we capture those parameters in tandem with the route parameters?

For example, if you have the route:

```
// search books
$router->get('/books/title/:title', 'Books@searchBooksByTitle');
```

Could append the URL to include some additional parameters like:

`https://localhost/books/title/Harry?sort=publish_date`

I am running into issues when I attempt that it says the requested route is not found, and I believe that is because its explicitly looking for a route to match with the query parameters on it.

**Comment by afgprogrammer** [comment]
@bradical1379 The issue is fixed. Now you can access your query params in the controllers:
```
$this->request->get('sort')
```
