### ISSUE TITLE
Multiple matched routes in $this-matchRouter

### ISSUE THREAD

**Issue by shakilkhan-hash** [afgprogrammer/php-mvc-simpel-rest-api#7]
When I had multiple routes like `auth/login`, `auth/:custom/` , `/:parent/:alias/`  and my current route is `auth/login/` i get all three routes in $this->matchRouter, it is possible to fix that?
![image](https://user-images.githubusercontent.com/77694098/105081585-a979f800-5a92-11eb-9302-49bd4ad6cbb0.png)
![image](https://user-images.githubusercontent.com/77694098/105081599-aed74280-5a92-11eb-94a0-e8a9e69dacb5.png)
![image](https://user-images.githubusercontent.com/77694098/105081624-b5fe5080-5a92-11eb-84ee-1fe8f9991dae.png)
where `/auth/alias` normally are `/:parent/:alias/`
Also I get all params from the routes:
![image](https://user-images.githubusercontent.com/77694098/105081690-ca424d80-5a92-11eb-8388-58120bd876bd.png)

**Comment by afgprogrammer** [comment]
@shakilkhan-hash I did not catch you right, what you want to do?
